services:
  structurizr:
    image: structurizr/lite:latest
    container_name: structurizr-lite
    volumes:
      - structurizr_data:/usr/local/structurizr
    restart: unless-stopped
    labels:
      - 'traefik.http.middlewares.AKQ2GjoHoE99DGlqSr4ZWd59LX2Y9aP4BTtkRzWA6EtZj3Vh3WClm9LAT7CD1TZS.basicauth.users=zu-diagrams:$2y$05$wiDVzADYDTP1Zuh7MzDIfuX0WgF85b7xZa4z.wzsQHvzkpFCKwMEa'

  uploader:
    build: ./uploader
    container_name: uploader
    volumes:
      - structurizr_data:/usr/local/structurizr
    restart: unless-stopped
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    labels:
      - 'traefik.http.middlewares.y9pWnyziYURh42Q60gZ1e6TKfkr3B7NSGBhTuFPdA1CT47Mz3NndWfh8JywqRFx0.basicauth.users=zu-diagrams:$2y$05$wiDVzADYDTP1Zuh7MzDIfuX0WgF85b7xZa4z.wzsQHvzkpFCKwMEa'
  

volumes:
  structurizr_data:
